config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'contacts#index'

  get '/lookup', to: 'contacts#lookup', as: 'lookup'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :first_name, :last_name, :url

  validates_presence_of :first_name, :last_name, :url
  validates_format_of :url, with: /[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}\z/

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/models/valid_email.rb
class ValidEmail < ApplicationRecord
  validates_uniqueness_of :email
  validates_format_of :email, with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact!, only: :lookup
  before_action :set_emails, only: :index

  def index
    @emails = ValidEmail.all
  end

  def lookup
    email_pool = Emails::GeneratorService.call(@contact)

    unless @email = ValidEmail.where(email: email_pool).first
      valid_email = Emails::LookupService.call(email_pool)
      @email = ValidEmail.find_or_create_by(email: valid_email) if valid_email.present?
    end

    set_emails if @email.present?
  end

  private

  def set_emails
    @emails = ValidEmail.all
  end

  def set_contact!
    @contact = Contact.new(contact_params)

    unless @contact.valid?
      @errors = @contact.errors.full_messages

      render :form_error
    end
  end

  def contact_params
    params.require(:contact).permit(
      :first_name,
      :last_name,
      :url,
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_email_list.html.erb
<% if emails.present? %>
  <h4 class="text-secondary">Results</h4>

  <ul class="list-unstyled">
    <% emails.each do |email| %>
      <li class="<%= email.id == found_email&.id ? 'text-success' : '' %> fs-4">
        <%= email.email %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/contacts/_form.html.erb
<%= form_for :contact, url: lookup_path, method: :get, remote: true, html: { :onsubmit => "onSubmit()" } do |f| %>
  <div class="form-group mb-3">
    <label for="contact_first_name" class="form-label">First Name</label>
    <%= f.text_field :first_name, required: true, class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <label for="contact_last_name" class="form-label">Last Name</label>
    <%= f.text_field :last_name, required: true, class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <label for="contact_url" class="form-label">URL</label>
    <%= f.text_field :url, required: true, class: 'form-control' %>
  </div>

  <div class="d-grid">
    <%= f.submit 'Search', id: 'submit-btn', class: 'btn btn-primary' %>
  </div>
<% end %>

<script>
  function onSubmit() {
    document.getElementById('submit-btn').value = 'Looking up...';
    document.getElementById('submit-btn').disabled = true;
    document.getElementById('lookup-notice').innerHTML = '';
  }
</script>

app/views/contacts/form_error.js.erb
<% if @errors.present? %>
  document.getElementById('lookup-notice').innerHTML = "<%= @errors.first %>";
<% end %>

document.getElementById('submit-btn').disabled = false;
document.getElementById('submit-btn').value = 'Search';

app/views/contacts/index.html.erb
<div class="container-sm mt-5" style="max-width: 600px;">
  <h3>E-Mail Validator</h3>

  <div id="lookup-notice" class="alert alert-light"></div>

  <%= render 'form' %>

  <div id="valid-emails-list" class="mt-5">
    <%= render 'email_list', emails: @emails, found_email: @email %>
  </div>
</div>

app/views/contacts/lookup.js.erb
<% if @email.present? %>
  document.getElementById('lookup-notice').innerHTML = 'Found an email!';
  document.getElementById('valid-emails-list').innerHTML = "<%= j render('email_list', emails: @emails, found_email: @email) %>";
<% else %>
  document.getElementById('lookup-notice').innerHTML = "Couldn't find any valid emails";
<% end %>

document.getElementById('submit-btn').disabled = false;
document.getElementById('submit-btn').value = 'Search';

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MailValidator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>